version:  "3.7"
services:

  webgoat:
    image: danmx/docker-owasp-webgoat
    ports:
      - "8081:8080"

  zap:
    image: owasp/zap2docker-stable
    ports:
      - "8080:8080"
      - "8090:8090"
#    environment:
#      ZAP_PORT: 8090
#    network_mode: "host"
    command:
      - zap-webswing.sh
    depends_on:
      - webgoat

